uint64 timestamp  # time since system start (microseconds)

uint32 mavid      # sender MAV_SYS_ID
float64 lat       # WGS84 latitude (degrees)
float64 lon       # WGS84 longitude (degrees)
float64 alt       # altitude AMSL (m)
float64 vx        # local NED velocity x (m/s)
float64 vy        # local NED velocity y (m/s)
float64 vz        # local NED velocity z (m/s)
float64 yaw       # heading in rad
float64 yawspeed  # yaw speed in rad/s
